version: '3'

services:
  # ビューワーサービス（常時稼働）
  nook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nook
    volumes:
      - ${OUTPUT_DIR}:/app/output
    ports:
      - "8080:8080"
    command: uv run python nook/functions/viewer/viewer.py
    restart: always
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - OUTPUT_DIR=/app/output
      - TZ=Asia/Tokyo
    labels: 
      ofelia.enabled: "true"
      ofelia.job-exec.collector-job.schedule: "0 0 7 * * *"
      ofelia.job-exec.collector-job.command: "uv run python main.py"

  # Ofeliaスケジューラー
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nook
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Tokyo
    restart: always
    labels:
      ofelia.job-local.test-job.schedule: "@every 1h"
      ofelia.job-local.test-job.command: "date"