[project]
name = "nook"
version = "0.1.0"
description = "Nook"
requires-python = ">=3.10"
dependencies = [
    "arxiv>=2.1.0",
    "beautifulsoup4==4.12.3",
    "constructs>=10.0.0,<11.0.0",
    "fastapi>=0.115.11",
    "feedparser==6.0.10",
    "google-genai==1.2.0",
    "httpx==0.27.2",
    "jinja2>=3.1.5",
    "markdown>=3.7",
    "praw==7.7.1",
    "python-dotenv==1.0.0",
    "regex==2023.12.25",
    "requests==2.31.0",
    "tenacity==9.0.0",
    "tqdm>=4.67.1",
    "uvicorn>=0.34.0",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nook"]

[tool.uv]
dev-dependencies = [
    "ruff==0.9.6",
]
[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
exclude = [".venv"]
select = [
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "E",  # pycodestyle errors
    "G",
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
    "EXE",
    "F",
    "SIM1",
    # Not included in flake8
    "LOG",
    "NPY",
    "PERF",
    "PGH004",
    "PIE794",
    "PIE800",
    "PIE804",
    "PIE807",
    "PIE810",
    "PLC0131", # type bivariance
    "PLC0132", # type param mismatch
    "PLC0205", # string as __slots__
    "PLE",
    "PLR0133", # constant comparison
    "PLR0206", # property with params
    "PLR1722", # use sys exit
    "PLW0129", # assert on string literal
    "PLW0406", # import self
    "PLW0711", # binary op exception
    "PLW1509", # preexec_fn not safe with threads
    "PLW3301", # nested min max
    "PT006", # TODO: enable more PT rules
    "PT022",
    "PT023",
    "PT024",
    "PT025",
    "PT026",
    "PYI",
    "RUF008", # mutable dataclass default
    "RUF015", # access first ele in constant time
    "RUF016", # type error non-integer index
    "RUF017",
    "TRY200", # TODO: migrate from deprecated alias
    "TRY302",
]
ignore = [
    "G004",
    "F821",
    "C401",
    "C408",
    "PERF203",
    "PERF401",
]
